#!/bin/bash
####################################################################
# Fast and Easy Web Server Installation
# This script help you to install and configure a Linux server with:
#	- TRAC
#	- SVN
#	- Iptables (Most secure)
#	- SSH (Change port by default and securitize)
#	- Apache
#	- Django (Web Framework of awesome Python)
#	- MySQL
#	- Mail Server
# Author: Rodrigo Augosto C. (coto) <contact@protoboard.cl>
# Help: Rodrigo Bustos L. <rbustosx@gmail.com>
# URL: http://protoboard.cl
# Created: Apr 1, 2010 
####################################################################


readonly base_path=`dirname "$0"`
if [ ! -f $base_path/config ]; then
	echo "Error: You must to create a '$base_path/config' file before, you can create it from '$base_path/config.sample' "
	exit
fi

if [ ! `whoami` = "root" ]; then 
	echo "Error: You must to be ROOT user to run this script"
	exit
fi

. "$base_path/config"
. "$base_path/functions/global.sh"
. "$base_path/lib/mailserver.sh"
. "$base_path/lib/cron-backup.sh"
. "$base_path/lib/dns.sh"
. "$base_path/lib/core.sh"

if [[ $DistroBasedOn = "debian" ]]; then
	. "$base_path/functions/debian.sh"
elif [[ $DistroBasedOn = "redhat" ]]; then
	. "$base_path/functions/redhat.sh"
else
	echo "Impossible to run this script in your computer, because it's not a recognizable distribution!!!"
fi

printMenu

# Run Cron Backup
#cronBackup
